### ISSUE TITLE
Ergebniseingabe KO über Tastatur

### ISSUE THREAD

**Issue by babbisch** [henshingly/lmo_php8#18]
kein Fehler an sich, lediglich UX

In dem letzten Release "springt" der Cursor in der Ergebniseingabe bei KO-Turnieren seltsam, wenn man mit dem Tabulator in das nächste Feld möchte. Hängt mit deiner vorgenommenen Änderung zusammen, die Ergebnisse so zu erfassen, wie auch die Partie stattgefunden hat.

Du musst hierfür den Tabindex ändern in den jeweiligen else-Zweigen.

**Comment by henshingly** [comment]
fixed with ba4ad9db2d1d24145c4ed73180e49ea637740ed8
Außerdem habe ich die Indexe für die Eingabe von Datum, Uhrzeit, Spielnotiz und Link zum Spielbericht angepasst. Nach der Eingabe der oberen Daten springt der Reiter zunächst unten zur Spieltagsauswahl, dann zum Ticker (Ja/Nein), zum Tickertext und schließlich zum Speichern-Button
Vielen Dank für Deinen Commit
I also adjusted the indexes for entering the date, time, game note and link to the game report. After entering the upper data, the tab first jumps to the match day selection at the bottom, then to the ticker (yes/no), the ticker text and finally to the save button
THX  for your commit
